# Machine Learning model for the tracker

## importing required libraries inside this

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import joblib

In [12]:
import random
from datetime import datetime

expenses = []

for month in range(1, 13):  # Months 1 to 12
    for _ in range(50):  # 10 expenses per month
        
        day = random.randint(1, 28)  # safe days
        amount = random.randint(100, 2000)  # random expense
        
        date = datetime(2026, month, day).isoformat()
        
        expenses.append({
            "date": date,
            "amount": amount
        })

# Preview first few entries
expenses

[{'date': '2026-01-19T00:00:00', 'amount': 1145},
 {'date': '2026-01-23T00:00:00', 'amount': 1082},
 {'date': '2026-01-16T00:00:00', 'amount': 690},
 {'date': '2026-01-21T00:00:00', 'amount': 1353},
 {'date': '2026-01-28T00:00:00', 'amount': 1416},
 {'date': '2026-01-05T00:00:00', 'amount': 384},
 {'date': '2026-01-28T00:00:00', 'amount': 1718},
 {'date': '2026-01-14T00:00:00', 'amount': 1223},
 {'date': '2026-01-13T00:00:00', 'amount': 1256},
 {'date': '2026-01-05T00:00:00', 'amount': 1088},
 {'date': '2026-01-06T00:00:00', 'amount': 455},
 {'date': '2026-01-18T00:00:00', 'amount': 118},
 {'date': '2026-01-10T00:00:00', 'amount': 1143},
 {'date': '2026-01-01T00:00:00', 'amount': 1433},
 {'date': '2026-01-08T00:00:00', 'amount': 876},
 {'date': '2026-01-15T00:00:00', 'amount': 1482},
 {'date': '2026-01-14T00:00:00', 'amount': 741},
 {'date': '2026-01-12T00:00:00', 'amount': 767},
 {'date': '2026-01-17T00:00:00', 'amount': 440},
 {'date': '2026-01-24T00:00:00', 'amount': 435},
 {'date': '2026-01-09T00:00:00', 'amount': 1119},
 {'date': '2026-01-24T00:00:00', 'amount': 1184},
 {'date': '2026-01-21T00:00:00', 'amount': 185},
 {'date': '2026-01-01T00:00:00', 'amount': 424},
 {'date': '2026-01-10T00:00:00', 'amount': 210},
 {'date': '2026-01-04T00:00:00', 'amount': 1468},
 {'date': '2026-01-03T00:00:00', 'amount': 899},
 {'date': '2026-01-10T00:00:00', 'amount': 1745},
 {'date': '2026-01-16T00:00:00', 'amount': 555},
 {'date': '2026-01-11T00:00:00', 'amount': 982},
 {'date': '2026-01-13T00:00:00', 'amount': 1576},
 {'date': '2026-01-11T00:00:00', 'amount': 564},
 {'date': '2026-01-14T00:00:00', 'amount': 1472},
 {'date': '2026-01-13T00:00:00', 'amount': 1261},
 {'date': '2026-01-07T00:00:00', 'amount': 1080},
 {'date': '2026-01-06T00:00:00', 'amount': 1640},
 {'date': '2026-01-12T00:00:00', 'amount': 1789},
 {'date': '2026-01-27T00:00:00', 'amount': 1509},
 {'date': '2026-01-25T00:00:00', 'amount': 548},
 {'date': '2026-01-21T00:00:00', 'amount': 866},
 {'date': '2026-01-21T00:00:00', 'amount': 594},
 {'date': '2026-01-04T00:00:00', 'amount': 763},
 {'date': '2026-01-10T00:00:00', 'amount': 1093},
 {'date': '2026-01-19T00:00:00', 'amount': 1569},
 {'date': '2026-01-03T00:00:00', 'amount': 1564},
 {'date': '2026-01-26T00:00:00', 'amount': 1901},
 {'date': '2026-01-22T00:00:00', 'amount': 312},
 {'date': '2026-01-09T00:00:00', 'amount': 595},
 {'date': '2026-01-09T00:00:00', 'amount': 1025},
 {'date': '2026-01-11T00:00:00', 'amount': 1782},
 {'date': '2026-02-26T00:00:00', 'amount': 1988},
 {'date': '2026-02-23T00:00:00', 'amount': 1048},
 {'date': '2026-02-20T00:00:00', 'amount': 412},
 {'date': '2026-02-01T00:00:00', 'amount': 1965},
 {'date': '2026-02-27T00:00:00', 'amount': 1442},
 {'date': '2026-02-10T00:00:00', 'amount': 687},
 {'date': '2026-02-15T00:00:00', 'amount': 1171},
 {'date': '2026-02-03T00:00:00', 'amount': 194},
 {'date': '2026-02-12T00:00:00', 'amount': 758},
 {'date': '2026-02-27T00:00:00', 'amount': 1173},
 {'date': '2026-02-19T00:00:00', 'amount': 1633},
 {'date': '2026-02-02T00:00:00', 'amount': 1781},
 {'date': '2026-02-07T00:00:00', 'amount': 369},
 {'date': '2026-02-04T00:00:00', 'amount': 186},
 {'date': '2026-02-26T00:00:00', 'amount': 405},
 {'date': '2026-02-05T00:00:00', 'amount': 568},
 {'date': '2026-02-15T00:00:00', 'amount': 1201},
 {'date': '2026-02-02T00:00:00', 'amount': 689},
 {'date': '2026-02-27T00:00:00', 'amount': 499},
 {'date': '2026-02-08T00:00:00', 'amount': 1521},
 {'date': '2026-02-10T00:00:00', 'amount': 1817},
 {'date': '2026-02-18T00:00:00', 'amount': 1714},
 {'date': '2026-02-27T00:00:00', 'amount': 500},
 {'date': '2026-02-14T00:00:00', 'amount': 1126},
 {'date': '2026-02-05T00:00:00', 'amount': 458},
 {'date': '2026-02-05T00:00:00', 'amount': 1079},
 {'date': '2026-02-09T00:00:00', 'amount': 1416},
 {'date': '2026-02-07T00:00:00', 'amount': 1599},
 {'date': '2026-02-21T00:00:00', 'amount': 479},
 {'date': '2026-02-24T00:00:00', 'amount': 915},
 {'date': '2026-02-17T00:00:00', 'amount': 1978},
 {'date': '2026-02-10T00:00:00', 'amount': 1099},
 {'date': '2026-02-13T00:00:00', 'amount': 1768},
 {'date': '2026-02-13T00:00:00', 'amount': 745},
 {'date': '2026-02-23T00:00:00', 'amount': 1546},
 {'date': '2026-02-25T00:00:00', 'amount': 1209},
 {'date': '2026-02-09T00:00:00', 'amount': 496},
 {'date': '2026-02-26T00:00:00', 'amount': 257},
 {'date': '2026-02-03T00:00:00', 'amount': 407},
 {'date': '2026-02-17T00:00:00', 'amount': 483},
 {'date': '2026-02-26T00:00:00', 'amount': 1356},
 {'date': '2026-02-17T00:00:00', 'amount': 1903},
 {'date': '2026-02-02T00:00:00', 'amount': 1290},
 {'date': '2026-02-27T00:00:00', 'amount': 1451},
 {'date': '2026-02-10T00:00:00', 'amount': 885},
 {'date': '2026-02-21T00:00:00', 'amount': 1853},
 {'date': '2026-02-25T00:00:00', 'amount': 191},
 {'date': '2026-02-14T00:00:00', 'amount': 436},
 {'date': '2026-02-21T00:00:00', 'amount': 1190},
 {'date': '2026-02-11T00:00:00', 'amount': 1132},
 {'date': '2026-03-23T00:00:00', 'amount': 745},
 {'date': '2026-03-12T00:00:00', 'amount': 543},
 {'date': '2026-03-15T00:00:00', 'amount': 1335},
 {'date': '2026-03-23T00:00:00', 'amount': 1967},
 {'date': '2026-03-01T00:00:00', 'amount': 249},
 {'date': '2026-03-25T00:00:00', 'amount': 1355},
 {'date': '2026-03-18T00:00:00', 'amount': 1765},
 {'date': '2026-03-08T00:00:00', 'amount': 1265},
 {'date': '2026-03-16T00:00:00', 'amount': 1366},
 {'date': '2026-03-13T00:00:00', 'amount': 925},
 {'date': '2026-03-18T00:00:00', 'amount': 750},
 {'date': '2026-03-04T00:00:00', 'amount': 1847},
 {'date': '2026-03-07T00:00:00', 'amount': 1424},
 {'date': '2026-03-28T00:00:00', 'amount': 1209},
 {'date': '2026-03-04T00:00:00', 'amount': 1447},
 {'date': '2026-03-04T00:00:00', 'amount': 1080},
 {'date': '2026-03-25T00:00:00', 'amount': 1538},
 {'date': '2026-03-28T00:00:00', 'amount': 1286},
 {'date': '2026-03-19T00:00:00', 'amount': 1840},
 {'date': '2026-03-24T00:00:00', 'amount': 1035},
 {'date': '2026-03-14T00:00:00', 'amount': 1294},
 {'date': '2026-03-21T00:00:00', 'amount': 234},
 {'date': '2026-03-28T00:00:00', 'amount': 702},
 {'date': '2026-03-16T00:00:00', 'amount': 980},
 {'date': '2026-03-05T00:00:00', 'amount': 1965},
 {'date': '2026-03-27T00:00:00', 'amount': 129},
 {'date': '2026-03-02T00:00:00', 'amount': 232},
 {'date': '2026-03-16T00:00:00', 'amount': 116},
 {'date': '2026-03-18T00:00:00', 'amount': 1136},
 {'date': '2026-03-03T00:00:00', 'amount': 353},
 {'date': '2026-03-19T00:00:00', 'amount': 672},
 {'date': '2026-03-07T00:00:00', 'amount': 1046},
 {'date': '2026-03-04T00:00:00', 'amount': 435},
 {'date': '2026-03-16T00:00:00', 'amount': 525},
 {'date': '2026-03-04T00:00:00', 'amount': 1909},
 {'date': '2026-03-01T00:00:00', 'amount': 1533},
 {'date': '2026-03-07T00:00:00', 'amount': 1812},
 {'date': '2026-03-15T00:00:00', 'amount': 603},
 {'date': '2026-03-15T00:00:00', 'amount': 237},
 {'date': '2026-03-17T00:00:00', 'amount': 1479},
 {'date': '2026-03-26T00:00:00', 'amount': 1318},
 {'date': '2026-03-21T00:00:00', 'amount': 1074},
 {'date': '2026-03-09T00:00:00', 'amount': 1043},
 {'date': '2026-03-18T00:00:00', 'amount': 1828},
 {'date': '2026-03-25T00:00:00', 'amount': 1389},
 {'date': '2026-03-03T00:00:00', 'amount': 676},
 {'date': '2026-03-09T00:00:00', 'amount': 1521},
 {'date': '2026-03-05T00:00:00', 'amount': 415},
 {'date': '2026-03-28T00:00:00', 'amount': 1658},
 {'date': '2026-03-23T00:00:00', 'amount': 672},
 {'date': '2026-04-06T00:00:00', 'amount': 622},
 {'date': '2026-04-20T00:00:00', 'amount': 101},
 {'date': '2026-04-28T00:00:00', 'amount': 1155},
 {'date': '2026-04-10T00:00:00', 'amount': 642},
 {'date': '2026-04-05T00:00:00', 'amount': 952},
 {'date': '2026-04-24T00:00:00', 'amount': 1345},
 {'date': '2026-04-24T00:00:00', 'amount': 988},
 {'date': '2026-04-08T00:00:00', 'amount': 1112},
 {'date': '2026-04-06T00:00:00', 'amount': 1293},
 {'date': '2026-04-25T00:00:00', 'amount': 690},
 {'date': '2026-04-21T00:00:00', 'amount': 1092},
 {'date': '2026-04-14T00:00:00', 'amount': 812},
 {'date': '2026-04-06T00:00:00', 'amount': 1239},
 {'date': '2026-04-04T00:00:00', 'amount': 459},
 {'date': '2026-04-18T00:00:00', 'amount': 205},
 {'date': '2026-04-08T00:00:00', 'amount': 1040},
 {'date': '2026-04-15T00:00:00', 'amount': 1615},
 {'date': '2026-04-23T00:00:00', 'amount': 1906},
 {'date': '2026-04-25T00:00:00', 'amount': 576},
 {'date': '2026-04-25T00:00:00', 'amount': 977},
 {'date': '2026-04-14T00:00:00', 'amount': 820},
 {'date': '2026-04-03T00:00:00', 'amount': 595},
 {'date': '2026-04-08T00:00:00', 'amount': 295},
 {'date': '2026-04-15T00:00:00', 'amount': 1733},
 {'date': '2026-04-01T00:00:00', 'amount': 1364},
 {'date': '2026-04-11T00:00:00', 'amount': 912},
 {'date': '2026-04-20T00:00:00', 'amount': 342},
 {'date': '2026-04-23T00:00:00', 'amount': 1132},
 {'date': '2026-04-22T00:00:00', 'amount': 1728},
 {'date': '2026-04-06T00:00:00', 'amount': 416},
 {'date': '2026-04-28T00:00:00', 'amount': 1407},
 {'date': '2026-04-20T00:00:00', 'amount': 362},
 {'date': '2026-04-07T00:00:00', 'amount': 1576},
 {'date': '2026-04-15T00:00:00', 'amount': 643},
 {'date': '2026-04-22T00:00:00', 'amount': 1230},
 {'date': '2026-04-15T00:00:00', 'amount': 1754},
 {'date': '2026-04-27T00:00:00', 'amount': 920},
 {'date': '2026-04-18T00:00:00', 'amount': 416},
 {'date': '2026-04-27T00:00:00', 'amount': 1872},
 {'date': '2026-04-26T00:00:00', 'amount': 969},
 {'date': '2026-04-06T00:00:00', 'amount': 1695},
 {'date': '2026-04-06T00:00:00', 'amount': 1039},
 {'date': '2026-04-28T00:00:00', 'amount': 1730},
 {'date': '2026-04-26T00:00:00', 'amount': 1365},
 {'date': '2026-04-20T00:00:00', 'amount': 1551},
 {'date': '2026-04-24T00:00:00', 'amount': 803},
 {'date': '2026-04-19T00:00:00', 'amount': 708},
 {'date': '2026-04-21T00:00:00', 'amount': 648},
 {'date': '2026-04-05T00:00:00', 'amount': 1203},
 {'date': '2026-04-24T00:00:00', 'amount': 513},
 {'date': '2026-05-01T00:00:00', 'amount': 743},
 {'date': '2026-05-24T00:00:00', 'amount': 1795},
 {'date': '2026-05-23T00:00:00', 'amount': 445},
 {'date': '2026-05-27T00:00:00', 'amount': 1651},
 {'date': '2026-05-15T00:00:00', 'amount': 518},
 {'date': '2026-05-07T00:00:00', 'amount': 1820},
 {'date': '2026-05-18T00:00:00', 'amount': 1586},
 {'date': '2026-05-08T00:00:00', 'amount': 411},
 {'date': '2026-05-07T00:00:00', 'amount': 1810},
 {'date': '2026-05-22T00:00:00', 'amount': 1096},
 {'date': '2026-05-15T00:00:00', 'amount': 530},
 {'date': '2026-05-13T00:00:00', 'amount': 472},
 {'date': '2026-05-05T00:00:00', 'amount': 199},
 {'date': '2026-05-10T00:00:00', 'amount': 1202},
 {'date': '2026-05-24T00:00:00', 'amount': 1908},
 {'date': '2026-05-16T00:00:00', 'amount': 1776},
 {'date': '2026-05-09T00:00:00', 'amount': 1265},
 {'date': '2026-05-26T00:00:00', 'amount': 1321},
 {'date': '2026-05-21T00:00:00', 'amount': 1388},
 {'date': '2026-05-05T00:00:00', 'amount': 1236},
 {'date': '2026-05-21T00:00:00', 'amount': 594},
 {'date': '2026-05-20T00:00:00', 'amount': 1747},
 {'date': '2026-05-08T00:00:00', 'amount': 393},
 {'date': '2026-05-16T00:00:00', 'amount': 1010},
 {'date': '2026-05-10T00:00:00', 'amount': 1035},
 {'date': '2026-05-24T00:00:00', 'amount': 940},
 {'date': '2026-05-19T00:00:00', 'amount': 1284},
 {'date': '2026-05-17T00:00:00', 'amount': 1599},
 {'date': '2026-05-25T00:00:00', 'amount': 804},
 {'date': '2026-05-12T00:00:00', 'amount': 216},
 {'date': '2026-05-23T00:00:00', 'amount': 1146},
 {'date': '2026-05-12T00:00:00', 'amount': 1627},
 {'date': '2026-05-14T00:00:00', 'amount': 796},
 {'date': '2026-05-15T00:00:00', 'amount': 470},
 {'date': '2026-05-25T00:00:00', 'amount': 1771},
 {'date': '2026-05-23T00:00:00', 'amount': 1490},
 {'date': '2026-05-22T00:00:00', 'amount': 1591},
 {'date': '2026-05-03T00:00:00', 'amount': 637},
 {'date': '2026-05-25T00:00:00', 'amount': 1587},
 {'date': '2026-05-21T00:00:00', 'amount': 1859},
 {'date': '2026-05-19T00:00:00', 'amount': 1896},
 {'date': '2026-05-08T00:00:00', 'amount': 1809},
 {'date': '2026-05-21T00:00:00', 'amount': 314},
 {'date': '2026-05-04T00:00:00', 'amount': 1418},
 {'date': '2026-05-14T00:00:00', 'amount': 102},
 {'date': '2026-05-06T00:00:00', 'amount': 1715},
 {'date': '2026-05-09T00:00:00', 'amount': 917},
 {'date': '2026-05-10T00:00:00', 'amount': 737},
 {'date': '2026-05-10T00:00:00', 'amount': 1139},
 {'date': '2026-05-17T00:00:00', 'amount': 1708},
 {'date': '2026-06-06T00:00:00', 'amount': 938},
 {'date': '2026-06-10T00:00:00', 'amount': 1153},
 {'date': '2026-06-10T00:00:00', 'amount': 887},
 {'date': '2026-06-07T00:00:00', 'amount': 649},
 {'date': '2026-06-07T00:00:00', 'amount': 1527},
 {'date': '2026-06-13T00:00:00', 'amount': 601},
 {'date': '2026-06-18T00:00:00', 'amount': 446},
 {'date': '2026-06-08T00:00:00', 'amount': 144},
 {'date': '2026-06-22T00:00:00', 'amount': 1859},
 {'date': '2026-06-09T00:00:00', 'amount': 1433},
 {'date': '2026-06-27T00:00:00', 'amount': 1772},
 {'date': '2026-06-07T00:00:00', 'amount': 467},
 {'date': '2026-06-27T00:00:00', 'amount': 1265},
 {'date': '2026-06-22T00:00:00', 'amount': 1041},
 {'date': '2026-06-15T00:00:00', 'amount': 926},
 {'date': '2026-06-02T00:00:00', 'amount': 1076},
 {'date': '2026-06-10T00:00:00', 'amount': 263},
 {'date': '2026-06-15T00:00:00', 'amount': 1786},
 {'date': '2026-06-17T00:00:00', 'amount': 1936},
 {'date': '2026-06-18T00:00:00', 'amount': 553},
 {'date': '2026-06-25T00:00:00', 'amount': 660},
 {'date': '2026-06-20T00:00:00', 'amount': 1137},
 {'date': '2026-06-04T00:00:00', 'amount': 630},
 {'date': '2026-06-23T00:00:00', 'amount': 1654},
 {'date': '2026-06-10T00:00:00', 'amount': 1621},
 {'date': '2026-06-17T00:00:00', 'amount': 571},
 {'date': '2026-06-03T00:00:00', 'amount': 1137},
 {'date': '2026-06-14T00:00:00', 'amount': 1213},
 {'date': '2026-06-19T00:00:00', 'amount': 1100},
 {'date': '2026-06-10T00:00:00', 'amount': 623},
 {'date': '2026-06-26T00:00:00', 'amount': 347},
 {'date': '2026-06-14T00:00:00', 'amount': 1648},
 {'date': '2026-06-14T00:00:00', 'amount': 1657},
 {'date': '2026-06-13T00:00:00', 'amount': 762},
 {'date': '2026-06-17T00:00:00', 'amount': 1883},
 {'date': '2026-06-25T00:00:00', 'amount': 1512},
 {'date': '2026-06-09T00:00:00', 'amount': 1708},
 {'date': '2026-06-27T00:00:00', 'amount': 448},
 {'date': '2026-06-20T00:00:00', 'amount': 1461},
 {'date': '2026-06-15T00:00:00', 'amount': 1328},
 {'date': '2026-06-21T00:00:00', 'amount': 1864},
 {'date': '2026-06-27T00:00:00', 'amount': 1798},
 {'date': '2026-06-11T00:00:00', 'amount': 912},
 {'date': '2026-06-25T00:00:00', 'amount': 324},
 {'date': '2026-06-11T00:00:00', 'amount': 1052},
 {'date': '2026-06-07T00:00:00', 'amount': 328},
 {'date': '2026-06-17T00:00:00', 'amount': 1125},
 {'date': '2026-06-25T00:00:00', 'amount': 369},
 {'date': '2026-06-01T00:00:00', 'amount': 1140},
 {'date': '2026-06-10T00:00:00', 'amount': 591},
 {'date': '2026-07-06T00:00:00', 'amount': 826},
 {'date': '2026-07-07T00:00:00', 'amount': 541},
 {'date': '2026-07-01T00:00:00', 'amount': 523},
 {'date': '2026-07-18T00:00:00', 'amount': 1479},
 {'date': '2026-07-20T00:00:00', 'amount': 512},
 {'date': '2026-07-08T00:00:00', 'amount': 327},
 {'date': '2026-07-28T00:00:00', 'amount': 1410},
 {'date': '2026-07-14T00:00:00', 'amount': 1479},
 {'date': '2026-07-16T00:00:00', 'amount': 1318},
 {'date': '2026-07-14T00:00:00', 'amount': 1759},
 {'date': '2026-07-15T00:00:00', 'amount': 565},
 {'date': '2026-07-27T00:00:00', 'amount': 292},
 {'date': '2026-07-14T00:00:00', 'amount': 1009},
 {'date': '2026-07-05T00:00:00', 'amount': 824},
 {'date': '2026-07-14T00:00:00', 'amount': 907},
 {'date': '2026-07-03T00:00:00', 'amount': 1460},
 {'date': '2026-07-21T00:00:00', 'amount': 497},
 {'date': '2026-07-12T00:00:00', 'amount': 429},
 {'date': '2026-07-10T00:00:00', 'amount': 799},
 {'date': '2026-07-27T00:00:00', 'amount': 661},
 {'date': '2026-07-12T00:00:00', 'amount': 1024},
 {'date': '2026-07-08T00:00:00', 'amount': 131},
 {'date': '2026-07-18T00:00:00', 'amount': 1208},
 {'date': '2026-07-11T00:00:00', 'amount': 742},
 {'date': '2026-07-27T00:00:00', 'amount': 183},
 {'date': '2026-07-25T00:00:00', 'amount': 950},
 {'date': '2026-07-05T00:00:00', 'amount': 1947},
 {'date': '2026-07-09T00:00:00', 'amount': 396},
 {'date': '2026-07-27T00:00:00', 'amount': 1985},
 {'date': '2026-07-21T00:00:00', 'amount': 1086},
 {'date': '2026-07-23T00:00:00', 'amount': 1321},
 {'date': '2026-07-08T00:00:00', 'amount': 1354},
 {'date': '2026-07-06T00:00:00', 'amount': 199},
 {'date': '2026-07-24T00:00:00', 'amount': 140},
 {'date': '2026-07-02T00:00:00', 'amount': 1815},
 {'date': '2026-07-11T00:00:00', 'amount': 1323},
 {'date': '2026-07-26T00:00:00', 'amount': 276},
 {'date': '2026-07-27T00:00:00', 'amount': 1210},
 {'date': '2026-07-10T00:00:00', 'amount': 609},
 {'date': '2026-07-14T00:00:00', 'amount': 1394},
 {'date': '2026-07-12T00:00:00', 'amount': 844},
 {'date': '2026-07-02T00:00:00', 'amount': 1701},
 {'date': '2026-07-25T00:00:00', 'amount': 1209},
 {'date': '2026-07-15T00:00:00', 'amount': 405},
 {'date': '2026-07-11T00:00:00', 'amount': 1443},
 {'date': '2026-07-12T00:00:00', 'amount': 1885},
 {'date': '2026-07-17T00:00:00', 'amount': 939},
 {'date': '2026-07-05T00:00:00', 'amount': 750},
 {'date': '2026-07-07T00:00:00', 'amount': 725},
 {'date': '2026-07-01T00:00:00', 'amount': 1355},
 {'date': '2026-08-19T00:00:00', 'amount': 1275},
 {'date': '2026-08-09T00:00:00', 'amount': 1627},
 {'date': '2026-08-12T00:00:00', 'amount': 402},
 {'date': '2026-08-05T00:00:00', 'amount': 1979},
 {'date': '2026-08-10T00:00:00', 'amount': 672},
 {'date': '2026-08-16T00:00:00', 'amount': 207},
 {'date': '2026-08-13T00:00:00', 'amount': 1251},
 {'date': '2026-08-06T00:00:00', 'amount': 1529},
 {'date': '2026-08-08T00:00:00', 'amount': 1383},
 {'date': '2026-08-23T00:00:00', 'amount': 958},
 {'date': '2026-08-09T00:00:00', 'amount': 940},
 {'date': '2026-08-13T00:00:00', 'amount': 310},
 {'date': '2026-08-23T00:00:00', 'amount': 1096},
 {'date': '2026-08-21T00:00:00', 'amount': 1470},
 {'date': '2026-08-23T00:00:00', 'amount': 1985},
 {'date': '2026-08-02T00:00:00', 'amount': 1787},
 {'date': '2026-08-05T00:00:00', 'amount': 277},
 {'date': '2026-08-10T00:00:00', 'amount': 690},
 {'date': '2026-08-18T00:00:00', 'amount': 193},
 {'date': '2026-08-17T00:00:00', 'amount': 1368},
 {'date': '2026-08-06T00:00:00', 'amount': 1975},
 {'date': '2026-08-10T00:00:00', 'amount': 418},
 {'date': '2026-08-21T00:00:00', 'amount': 251},
 {'date': '2026-08-27T00:00:00', 'amount': 1004},
 {'date': '2026-08-12T00:00:00', 'amount': 409},
 {'date': '2026-08-02T00:00:00', 'amount': 626},
 {'date': '2026-08-05T00:00:00', 'amount': 561},
 {'date': '2026-08-15T00:00:00', 'amount': 1865},
 {'date': '2026-08-12T00:00:00', 'amount': 948},
 {'date': '2026-08-03T00:00:00', 'amount': 1409},
 {'date': '2026-08-28T00:00:00', 'amount': 1357},
 {'date': '2026-08-10T00:00:00', 'amount': 318},
 {'date': '2026-08-19T00:00:00', 'amount': 676},
 {'date': '2026-08-01T00:00:00', 'amount': 959},
 {'date': '2026-08-23T00:00:00', 'amount': 151},
 {'date': '2026-08-05T00:00:00', 'amount': 356},
 {'date': '2026-08-14T00:00:00', 'amount': 1144},
 {'date': '2026-08-17T00:00:00', 'amount': 1206},
 {'date': '2026-08-04T00:00:00', 'amount': 130},
 {'date': '2026-08-28T00:00:00', 'amount': 208},
 {'date': '2026-08-10T00:00:00', 'amount': 1558},
 {'date': '2026-08-27T00:00:00', 'amount': 1988},
 {'date': '2026-08-05T00:00:00', 'amount': 879},
 {'date': '2026-08-23T00:00:00', 'amount': 1485},
 {'date': '2026-08-19T00:00:00', 'amount': 851},
 {'date': '2026-08-22T00:00:00', 'amount': 894},
 {'date': '2026-08-27T00:00:00', 'amount': 1964},
 {'date': '2026-08-16T00:00:00', 'amount': 969},
 {'date': '2026-08-19T00:00:00', 'amount': 534},
 {'date': '2026-08-23T00:00:00', 'amount': 822},
 {'date': '2026-09-12T00:00:00', 'amount': 345},
 {'date': '2026-09-17T00:00:00', 'amount': 812},
 {'date': '2026-09-03T00:00:00', 'amount': 708},

In [13]:
df = pd.DataFrame(expenses)
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.month

df

          date  amount  month
0   2026-01-19    1145      1
1   2026-01-23    1082      1
2   2026-01-16     690      1
3   2026-01-21    1353      1
4   2026-01-28    1416      1
..         ...     ...    ...
595 2026-12-17     764     12
596 2026-12-02     389     12
597 2026-12-26    1262     12
598 2026-12-09    1936     12
599 2026-12-18    1035     12

[600 rows x 3 columns]

In [14]:
monthly = df.groupby('month')['amount'].sum().reset_index()
monthly = monthly.sort_values(by='month')

monthly

    month  amount
0       1   51519
1       2   52468
2       3   53957
3       4   50562
4       5   57523
5       6   53325
6       7   48166
7       8   49314
8       9   47379
9      10   45119
10     11   54100
11     12   55541

In [15]:
all_months = pd.DataFrame({'month': range(1, 13)})
monthly = all_months.merge(monthly, on='month', how='left').fillna(0)

monthly

    month  amount
0       1   51519
1       2   52468
2       3   53957
3       4   50562
4       5   57523
5       6   53325
6       7   48166
7       8   49314
8       9   47379
9      10   45119
10     11   54100
11     12   55541

In [16]:
X = monthly[['month']]
y = monthly['amount']

X
y

0     51519
1     52468
2     53957
3     50562
4     57523
5     53325
6     48166
7     49314
8     47379
9     45119
10    54100
11    55541
Name: amount, dtype: int64

In [17]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [18]:
next_month = [[13]] # predicting after month 12
prediction = model.predict(next_month)

print("Predicted next month expense: ", prediction)

Predicted next month expense:  [50475.6969697]

C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [19]:
joblib.dump(model, "model.pkl")

['model.pkl']